In [207]:
import pandas as pd
import numpy as np

In [208]:
df = pd.read_csv('../../../data/clean_data/salaries_descriptions_locations_gramcounts.csv')

In [209]:
df.shape

(854, 147)

In [210]:
df.head()

,Unnamed: 0,Country,Description,Glassdoor Salary Estimate,Position_clean,base_pay,bonus_pay,cash_bonus,company,company_industry_Accounting,...,"('qualified', 'applicants', 'receive')","('protected', 'veteran', 'status')","('All', 'qualified', 'applicants')","('natural', 'language', 'processing')","('gender', 'gender', 'identity')","('2', 'years', 'experience')","('color', 'national', 'origin')","('people', 'around', 'world')","('color', 'religion', 'sex')","('Senior', 'Data', 'Scientist')"
0,0,US,Facebook's mission is to give people the power...,193225.0,Data Scientist,198153.22,19650.0,19650.0,Facebook,0.0,...,0,1,0,0,1,0,1,1,0,0
1,1,US,Facebook's mission is to give people the power...,193225.0,Data Scientist,198153.22,19650.0,19650.0,Facebook,0.0,...,0,1,0,0,1,0,1,1,0,0
2,2,US,Facebook's mission is to give people the power...,184055.0,Data Scientist,198153.22,19650.0,19650.0,Facebook,0.0,...,0,1,0,0,1,0,1,1,0,0
3,3,US,Facebook's mission is to give people the power...,184055.0,Data Scientist,198153.22,19650.0,19650.0,Facebook,0.0,...,0,1,0,0,1,0,1,1,0,0
4,4,US,Facebook's mission is to give people the power...,184055.0,Data Scientist,198153.22,19650.0,19650.0,Facebook,0.0,...,0,1,0,0,1,0,1,1,0,0

In [211]:
df.columns

Index(['Unnamed: 0', 'Country', 'Description', 'Glassdoor Salary Estimate',
       'Position_clean', 'base_pay', 'bonus_pay', 'cash_bonus', 'company',
       'company_industry_Accounting',
       ...
       '('qualified', 'applicants', 'receive')',
       '('protected', 'veteran', 'status')',
       '('All', 'qualified', 'applicants')',
       '('natural', 'language', 'processing')',
       '('gender', 'gender', 'identity')', '('2', 'years', 'experience')',
       '('color', 'national', 'origin')', '('people', 'around', 'world')',
       '('color', 'religion', 'sex')', '('Senior', 'Data', 'Scientist')'],
      dtype='object', length=147)

In [212]:
country_encoding = pd.get_dummies(df.Country, prefix='Country')

In [213]:
df = df.merge(country_encoding,left_index=True,right_index=True)

In [214]:
df = df.drop(['Country','Description','company','base_pay','Glassdoor Salary Estimate'],axis=1)

In [215]:
remote_ind = []
for index,row in df.iterrows():
    if row['company_location'] == 'Remote':
        remote_ind.append(1)
    else:
        remote_ind.append(0)

In [216]:
df['Remote'] = remote_ind
df = df.drop(['company_location'],axis=1)

In [217]:
df.isnull().sum()

Unnamed: 0                                                    0
Position_clean                                                0
bonus_pay                                                   209
cash_bonus                                                  516
company_industry_Accounting                                  22
company_industry_Advertising & Marketing                      0
company_industry_Aerospace & Defense                          0
company_industry_Airlines                                   754
company_industry_Architectural & Engineering Services        22
company_industry_Banks & Credit Unions                        0
company_industry_Beauty & Personal Accessories Stores       122
company_industry_Biotech & Pharmaceuticals                    0
company_industry_Brokerage Services                          22
company_industry_Building & Personnel Services              122
company_industry_Cable, Internet & Telephone Providers        0
company_industry_Chemical Manufacturing                     122
company_industry_Colleges & Universities                      0
company_industry_Computer Hardware & Software                 0
company_industry_Consulting                                   0
company_industry_Department, Clothing, & Shoe Stores          0
company_industry_Education Training Services                100
company_industry_Electrical & Electronic Manufacturing       22
company_industry_Energy                                     100
company_industry_Enterprise Software & Network Solutions      0
company_industry_Federal Agencies                             0
company_industry_Financial Analytics & Research             100
company_industry_Food & Beverage Manufacturing              100
company_industry_Food & Beverage Stores                      22
company_industry_Grocery Stores & Supermarkets               22
company_industry_Health Care Products Manufacturing         122
                                                           ...
('data', 'sets')                                              0
('deep', 'learning')                                          0
('communication', 'skills')                                   0
('orientation', 'gender')                                     0
('Experience', 'working')                                     0
('without', 'regard')                                         0
('sexual', 'orientation', 'gender')                           0
('race', 'color', 'religion')                                 0
('orientation', 'gender', 'identity')                         0
('without', 'regard', 'race')                                 0
('regard', 'race', 'color')                                   0
('employment', 'without', 'regard')                           0
('receive', 'consideration', 'employment')                    0
('consideration', 'employment', 'without')                    0
('equal', 'opportunity', 'employer')                          0
('applicants', 'receive', 'consideration')                    0
('qualified', 'applicants', 'receive')                        0
('protected', 'veteran', 'status')                            0
('All', 'qualified', 'applicants')                            0
('natural', 'language', 'processing')                         0
('gender', 'gender', 'identity')                              0
('2', 'years', 'experience')                                  0
('color', 'national', 'origin')                               0
('people', 'around', 'world')                                 0
('color', 'religion', 'sex')                                  0
('Senior', 'Data', 'Scientist')                               0
Country_CA                                                    0
Country_UK                                                    0
Country_US                                                    0
Remote                                                        0
Length: 145, dtype: int64

In [218]:
df = df.fillna(0)

In [219]:
def position_map(pos_hierarchy,df):
    pos_mapping = {'Data Scientist Intern':pos_hierarchy[0],
               'Junior Data Scientist':pos_hierarchy[1],
               'Data Scientist':pos_hierarchy[2],
               'Senior Data Scientist':pos_hierarchy[3],
               'Lead Data Scientist':pos_hierarchy[4]}
    
    df_mapped = df.replace({'Position_clean':pos_mapping})
    return df_mapped

In [220]:
pos_ranks = [1,2,3,4,5]
df = position_map(pos_ranks,df)

In [221]:
df

,Unnamed: 0,Position_clean,bonus_pay,cash_bonus,company_industry_Accounting,company_industry_Advertising & Marketing,company_industry_Aerospace & Defense,company_industry_Airlines,company_industry_Architectural & Engineering Services,company_industry_Banks & Credit Unions,...,"('gender', 'gender', 'identity')","('2', 'years', 'experience')","('color', 'national', 'origin')","('people', 'around', 'world')","('color', 'religion', 'sex')","('Senior', 'Data', 'Scientist')",Country_CA,Country_UK,Country_US,Remote
0,0,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
1,1,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
2,2,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
3,3,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
4,4,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
5,5,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
6,6,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
7,7,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,1
8,8,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,1,1,1,0,0,0,0,1,0
9,9,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
10,10,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
11,11,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
12,12,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
13,13,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
14,14,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
15,15,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
16,16,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,1
17,17,3,19650.00,19650.00,0.0,0,0,0.0,0.0,0,...,1,1,1,1,0,0,0,0,1,0
18,18,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
19,19,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
20,20,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
21,21,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
22,22,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
23,23,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
24,24,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
25,25,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,1
26,26,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,1,1,1,1,0,0,0,0,1,0
27,27,3,16001.65,16001.65,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
28,28,3,16001.65,16001.65,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
29,29,3,16001.65,16001.65,0.0,0,0,0.0,0.0,0,...,1,0,1,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,824,5,129630.00,16530.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
825,825,5,129630.00,16530.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
826,826,5,129630.00,16530.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
827,827,5,129630.00,16530.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
828,828,5,129630.00,16530.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
829,829,4,68730.00,0.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,1,0,1,0,0
830,830,4,68730.00,0.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,1,0,1,0,0
831,831,4,68730.00,0.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,1,0,1,0,0
832,832,1,0.00,0.00,0.0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,1,0,0,0
833,833,1,0.00,0.00,0.0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,1,0,0,0
834,834,1,26.00,0.00,0.0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,1,0,0,0
835,835,1,0.00,0.00,0.0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,1,0,0,0
836,836,1,0.00,0.00,0.0,0,0,0.0,0.0,1,...,0,0,0,0,0,0,1,0,0,0
837,837,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
838,838,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
839,839,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
840,840,3,101500.00,15000.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
841,841,3,101500.00,15000.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
842,842,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,0,1,0,0,0,0,1,0,0,0
843,843,3,0.00,0.00,0.0,0,0,0.0,0.0,0,...,0,1,0,0,0,0,1,0,0,0
844,844,3,147000.00,0.00,0.0,0,0,0.0,0.0,0,...,0,1,0,0,0,0,1,0,0,0
845,845,3,147000.00,0.00,0.0,0,0,0.0,0.0,0,...,0,1,0,0,0,0,1,0,0,0
846,846,3,112500.00,10500.00,0.0,0,0,0.0,0.0,0,...,0,0,1,0,0,0,1,0,0,0
847,847,3,5000.00,0.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
848,848,3,5000.00,0.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
849,849,4,93500.00,55000.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
850,850,4,93500.00,55000.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
851,851,4,93500.00,55000.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
852,852,4,104000.00,3500.00,0.0,0,0,0.0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
853,853,4,104000.00,3500.00,0.0,0,0,0.0,0.0,0,...,0,1,0,0,0,0,1,0,0,0

In [222]:
normalized_df=(df-df.mean())/df.std()

In [223]:
mask = np.random.rand(len(normalized_df))<0.8
train_norm = normalized_df[mask]
test_norm = normalized_df[~mask]

train = df[mask]
test = df[~mask]

In [225]:
train.to_csv('../../../data/clean_data/train.csv')
test.to_csv('../../../data/clean_data/test.csv')

train_norm.to_csv('../../../data/clean_data/train_normalized.csv')
test_norm.to_csv('../../../data/clean_data/test_normalized.csv')